<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\core\RealtimeChat.Application\RealtimeChat.Application.csproj" />
    <ProjectReference Include="..\..\src\infrastructure\RealtimeChat.DependencyInjection\RealtimeChat.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\infrastructure\RealtimeChat.Infrastructure\RealtimeChat.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\infrastructure\RealtimeChat.Persistence\RealtimeChat.Persistence.csproj" />
  </ItemGroup>

</Project>
