<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\RealtimeChat.Application\RealtimeChat.Application.csproj" />
    <ProjectReference Include="..\..\core\RealtimeChat.Common\RealtimeChat.Common.csproj" />
    <ProjectReference Include="..\..\core\RealtimeChat.Contracts\RealtimeChat.Contracts.csproj" />
    <ProjectReference Include="..\..\core\RealtimeChat.Domain\RealtimeChat.Domain.csproj" />
  </ItemGroup>

</Project>
